/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-04-08T03:39:39.495641980+00:00
/// Collection: lucide
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/lucide/>
///
/// ```yaml
/// name: Lucide
/// author:
///   name: Lucide Contributors
///   url: https://github.com/lucide-icons/lucide
/// license:
///   title: ISC
///   spdx: ISC
///   url: https://github.com/lucide-icons/lucide/blob/main/LICENSE
/// total: 1694
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const BookText: IconData = IconData {
    name: "lucide:book-text",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20M8 11h8M8 7h6"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const CircleArrowRight: IconData = IconData {
    name: "lucide:circle-arrow-right",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="m12 16l4-4l-4-4m-4 4h8"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const CircleCheck: IconData = IconData {
    name: "lucide:circle-check",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="m9 12l2 2l4-4"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const CircleX: IconData = IconData {
    name: "lucide:circle-x",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="m15 9l-6 6m0-6l6 6"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Clipboard: IconData = IconData {
    name: "lucide:clipboard",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Download: IconData = IconData {
    name: "lucide:download",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M12 15V3m9 12v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10l5 5l5-5"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Ellipsis: IconData = IconData {
    name: "lucide:ellipsis",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Eye: IconData = IconData {
    name: "lucide:eye",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M2.062 12.348a1 1 0 0 1 0-.696a10.75 10.75 0 0 1 19.876 0a1 1 0 0 1 0 .696a10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const EyeOff: IconData = IconData {
    name: "lucide:eye-off",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575a1 1 0 0 1 0 .696a10.8 10.8 0 0 1-1.444 2.49m-6.41-.679a3 3 0 0 1-4.242-4.242"/><path d="M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151a1 1 0 0 1 0-.696a10.75 10.75 0 0 1 4.446-5.143M2 2l20 20"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Github: IconData = IconData {
    name: "lucide:github",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5c.08-1.25-.27-2.48-1-3.5c.28-1.15.28-2.35 0-3.5c0 0-1 0-3 1.5c-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5c-.39.49-.68 1.05-.85 1.65S8.93 17.38 9 18v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Globe: IconData = IconData {
    name: "lucide:globe",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20a14.5 14.5 0 0 0 0-20M2 12h20"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Pause: IconData = IconData {
    name: "lucide:pause",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="5" height="18" x="14" y="3" rx="1"/><rect width="5" height="18" x="5" y="3" rx="1"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Play: IconData = IconData {
    name: "lucide:play",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Redo: IconData = IconData {
    name: "lucide:redo",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M21 7v6h-6"/><path d="M3 17a9 9 0 0 1 9-9a9 9 0 0 1 6 2.3l3 2.7"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Server: IconData = IconData {
    name: "lucide:server",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="20" height="8" x="2" y="2" rx="2" ry="2"/><rect width="20" height="8" x="2" y="14" rx="2" ry="2"/><path d="M6 6h.01M6 18h.01"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Settings: IconData = IconData {
    name: "lucide:settings",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0a2.34 2.34 0 0 0 3.319 1.915a2.34 2.34 0 0 1 2.33 4.033a2.34 2.34 0 0 0 0 3.831a2.34 2.34 0 0 1-2.33 4.033a2.34 2.34 0 0 0-3.319 1.915a2.34 2.34 0 0 1-4.659 0a2.34 2.34 0 0 0-3.32-1.915a2.34 2.34 0 0 1-2.33-4.033a2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"/><circle cx="12" cy="12" r="3"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const SkipBack: IconData = IconData {
    name: "lucide:skip-back",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.971 4.285A2 2 0 0 1 21 6v12a2 2 0 0 1-3.029 1.715l-9.997-5.998a2 2 0 0 1-.003-3.432zM3 20V4"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const SkipForward: IconData = IconData {
    name: "lucide:skip-forward",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 4v16M6.029 4.285A2 2 0 0 0 3 6v12a2 2 0 0 0 3.029 1.715l9.997-5.998a2 2 0 0 0 .003-3.432z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const SquareArrowOutUpRight: IconData = IconData {
    name: "lucide:square-arrow-out-up-right",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6m10 0l-9 9m3-9h6v6"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Star: IconData = IconData {
    name: "lucide:star",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.12 2.12 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.12 2.12 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.12 2.12 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.12 2.12 0 0 0 1.597-1.16z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const StarOff: IconData = IconData {
    name: "lucide:star-off",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m10.344 4.688l1.181-2.393a.53.53 0 0 1 .95 0l2.31 4.679a2.12 2.12 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.237 3.152m-.658 4.999l.43 2.505a.53.53 0 0 1-.771.56l-4.618-2.428a2.12 2.12 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.12 2.12 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a8 8 0 0 0 .4-.099M2 2l20 20"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const StepBack: IconData = IconData {
    name: "lucide:step-back",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.971 4.285A2 2 0 0 1 17 6v12a2 2 0 0 1-3.029 1.715l-9.997-5.998a2 2 0 0 1-.003-3.432zM21 20V4"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const StepForward: IconData = IconData {
    name: "lucide:step-forward",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.029 4.285A2 2 0 0 0 7 6v12a2 2 0 0 0 3.029 1.715l9.997-5.998a2 2 0 0 0 .003-3.432zM3 4v16"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Undo: IconData = IconData {
    name: "lucide:undo",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M3 7v6h6"/><path d="M21 17a9 9 0 0 0-9-9a9 9 0 0 0-6 2.3L3 13"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
